import os

def design_system_architecture(system_name="scalable_backend"):
    """
    Jarvis acts as a Senior Solutions Architect.
    Generates Mermaid.js diagrams and system design documentation.
    """
    project_dir = "architecture_docs"
    if not os.path.exists(project_dir):
        os.makedirs(project_dir)

    safe_name = system_name.replace(" ", "_").lower()
    file_path = os.path.join(project_dir, f"{safe_name}_design.md")

    markdown_content = f"""# System Architecture: {system_name.title()}
*Generated by Jarvis Architect Module*

## 1. High-Level System Diagram
This diagram maps out the microservices, databases, and load balancers.
(You can paste this code into [Mermaid Live Editor](https://mermaid.live) to visualize it).

```mermaid
graph TD
    Client[Web / Mobile Client] -->|HTTPS| CDN[Cloudflare CDN]
    CDN --> API_GW[API Gateway / Load Balancer]
    
    API_GW -->|REST/GraphQL| Auth[Auth Service]
    API_GW -->|REST| CoreAPI[Core Application API]
    API_GW -->|WebSocket| RealTime[Real-time Service]
    
    Auth --> Redis[(Redis Session Cache)]
    CoreAPI --> DB[(PostgreSQL Database)]
    CoreAPI --> S3[S3 Object Storage]
    
    RealTime --> Kafka[Kafka Event Bus]
    Kafka --> Analytics[Data Analytics Pipeline]
```

## 2. Infrastructure Choices
* **Database**: PostgreSQL (Relational consistency) + Redis (High-speed caching).
* **Compute**: Docker Containers running on Kubernetes (K8s) or AWS ECS.
* **Messaging**: Apache Kafka for asynchronous event-driven communication.
"""

    with open(file_path, "w") as f:
        f.write(markdown_content)

    return f"📐 [ARCHITECT] I have designed the system architecture for '{system_name}'. Diagram saved at {file_path}."

if __name__ == "__main__":
    print(design_system_architecture())
