import os

def scaffold_3d_website(project_name="my_3d_website"):
    """
    Jarvis generates an interactive 3D website using Three.js 
    (similar to high-end modern sites like igloo.inc).
    """
    if not os.path.exists(project_name):
        os.makedirs(project_name)

    html_code = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jarvis Generated 3D Web</title>
    <style>
        body { margin: 0; overflow: hidden; background-color: #050505; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }
        #canvas-container { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; }
        .content { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center; pointer-events: none; }
        h1 { font-size: 4rem; letter-spacing: 5px; text-transform: uppercase; margin: 0; text-shadow: 0 0 20px rgba(255,255,255,0.2); }
        p { font-size: 1.2rem; color: #888; letter-spacing: 2px; }
    </style>
    <!-- Import Three.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
</head>
<body>

    <div class="content">
        <h1>FUTURE WEB</h1>
        <p>GENERATED BY JARVIS</p>
    </div>
    
    <div id="canvas-container"></div>

    <script>
        // 1. Scene Setup
        const scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
        const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
        
        renderer.setSize(window.innerWidth, window.innerHeight);
        document.getElementById('canvas-container').appendChild(renderer.domElement);

        // 2. Create an Interactive 3D Particle Mesh (Like Igloo.inc / high end sites)
        const geometry = new THREE.IcosahedronGeometry(2, 1);
        
        // Wireframe material
        const material = new THREE.MeshBasicMaterial({ 
            color: 0x00ffcc, 
            wireframe: true,
            transparent: true,
            opacity: 0.3
        });
        
        const sphere = new THREE.Mesh(geometry, material);
        scene.add(sphere);

        // Add floating particles
        const particlesGeometry = new THREE.BufferGeometry();
        const particlesCount = 700;
        const posArray = new Float32Array(particlesCount * 3);
        
        for(let i = 0; i < particlesCount * 3; i++) {
            posArray[i] = (Math.random() - 0.5) * 15;
        }
        
        particlesGeometry.setAttribute('position', new THREE.BufferAttribute(posArray, 3));
        const particlesMaterial = new THREE.PointsMaterial({
            size: 0.02,
            color: 0xffffff,
            transparent: true,
            opacity: 0.5
        });
        
        const particlesMesh = new THREE.Points(particlesGeometry, particlesMaterial);
        scene.add(particlesMesh);

        camera.position.z = 5;

        // 3. Mouse Interaction
        let mouseX = 0;
        let mouseY = 0;
        document.addEventListener('mousemove', (event) => {
            mouseX = event.clientX / window.innerWidth - 0.5;
            mouseY = event.clientY / window.innerHeight - 0.5;
        });

        // 4. Animation Loop
        function animate() {
            requestAnimationFrame(animate);
            
            // Rotate the main shape
            sphere.rotation.x += 0.002;
            sphere.rotation.y += 0.002;
            
            // Interactive rotation based on mouse
            sphere.rotation.x += mouseY * 0.05;
            sphere.rotation.y += mouseX * 0.05;
            
            // Rotate particles slowly
            particlesMesh.rotation.y -= 0.001;
            
            renderer.render(scene, camera);
        }
        
        animate();

        // Handle Window Resize
        window.addEventListener('resize', () => {
            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();
            renderer.setSize(window.innerWidth, window.innerHeight);
        });
    </script>
</body>
</html>
"""
    file_path = os.path.join(project_name, "index.html")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_code)
        
    return f"Success! Interactive 3D website generated at {file_path}"

if __name__ == "__main__":
    import sys
    name = sys.argv[1] if len(sys.argv) > 1 else "generated_3d_web"
    print(scaffold_3d_website(name))
